# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import darknet_detection_pb2 as darknet__detection__pb2


class DarknetDetectionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.darknetDetection = channel.unary_unary(
        '/darknet_detection.DarknetDetection/darknetDetection',
        request_serializer=darknet__detection__pb2.Image.SerializeToString,
        response_deserializer=darknet__detection__pb2.Detection.FromString,
        )


class DarknetDetectionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def darknetDetection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DarknetDetectionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'darknetDetection': grpc.unary_unary_rpc_method_handler(
          servicer.darknetDetection,
          request_deserializer=darknet__detection__pb2.Image.FromString,
          response_serializer=darknet__detection__pb2.Detection.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'darknet_detection.DarknetDetection', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
